services:
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CATALOG_URL=http://catalog:3001
      - ORDERS_URL=http://orders:3002
    depends_on:
      - catalog
      - orders
    networks:
      - plataforma-network

  catalog:
    build:
      context: ./services/catalog
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - plataforma-network

  orders:
    build:
      context: ./services/orders
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - CATALOG_URL=http://catalog:3001
      - NODE_ENV=production
    depends_on:
      - catalog
    networks:
      - plataforma-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=plataforma_pedidos
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - plataforma-network

networks:
  plataforma-network:
    driver: bridge

volumes:
  postgres-data: